// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientTrackerWPF.Data;

#nullable disable

namespace PatientTrackerWPF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250612171942_UpdatedScoreEntryWithAuditFields")]
    partial class UpdatedScoreEntryWithAuditFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PatientTrackerWPF.Models.ScoreEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BDI2")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GAD7")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PCL5")
                        .HasColumnType("int");

                    b.Property<int>("PHQ9")
                        .HasColumnType("int");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YBOCS")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_ScoreEntry_Date");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_ScoreEntry_PatientId");

                    b.HasIndex("PatientId", "Date")
                        .HasDatabaseName("IX_ScoreEntry_PatientId_Date");

                    b.ToTable("ScoreEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_ScoreEntry_BDI2_Range", "[BDI2] >= 0 AND [BDI2] <= 100");

                            t.HasCheckConstraint("CK_ScoreEntry_GAD7_Range", "[GAD7] >= 0 AND [GAD7] <= 100");

                            t.HasCheckConstraint("CK_ScoreEntry_PCL5_Range", "[PCL5] >= 0 AND [PCL5] <= 100");

                            t.HasCheckConstraint("CK_ScoreEntry_PHQ9_Range", "[PHQ9] >= 0 AND [PHQ9] <= 100");

                            t.HasCheckConstraint("CK_ScoreEntry_YBOCS_Range", "[YBOCS] >= 0 AND [YBOCS] <= 100");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
