// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientTrackerWPF.Data;

#nullable disable

namespace PatientTrackerWPF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250704203926_FixCascadeConflicts")]
    partial class FixCascadeConflicts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PatientTrackerWPF.Models.ScoreEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BDI2")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GAD7")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("PCL5")
                        .HasColumnType("int");

                    b.Property<int?>("PHQ9")
                        .HasColumnType("int");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("YBOCS")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_ScoreEntry_CreatedByUserId");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_ScoreEntry_Date");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_ScoreEntry_PatientId");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("IX_ScoreEntry_UpdatedByUserId");

                    b.HasIndex("PatientId", "Date")
                        .HasDatabaseName("IX_ScoreEntry_PatientId_Date");

                    b.ToTable("ScoreEntries", (string)null);
                });

            modelBuilder.Entity("PatientTrackerWPF.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PasswordResetExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("User");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Username");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Email = "admin@mentalhealth.clinic",
                            FailedLoginAttempts = 0,
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "dX1BlT191I7AM5wWntGH8/3xkkDyiS6noRsuOogGHKw=",
                            Role = "Admin",
                            Salt = "Q2tL8K9mN5pR7sT1vW3xZ6cF4hJ2kM8q",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Email = "dr.smith@mentalhealth.clinic",
                            FailedLoginAttempts = 0,
                            FullName = "Dr. John Smith",
                            IsActive = true,
                            PasswordHash = "uZhFenZ9S3QNv/n2IMjMww59FHNmF4cemZT1bwJHOnY=",
                            Role = "Doctor",
                            Salt = "A1bC3dE5fG7hI9jK2lM4nO6pQ8rS0tU",
                            Username = "dr.smith"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "System",
                            Email = "nurse.jane@mentalhealth.clinic",
                            FailedLoginAttempts = 0,
                            FullName = "Jane Doe, RN",
                            IsActive = true,
                            PasswordHash = "L9arRXBEO+qbMKDPDpN8+84S4mDbFF0OOqw9AH0Wyrk=",
                            Role = "Nurse",
                            Salt = "X1yZ3aB5cD7eF9gH2iJ4kL6mN8oP0qR",
                            Username = "nurse.jane"
                        });
                });

            modelBuilder.Entity("PatientTrackerWPF.Models.ScoreEntry", b =>
                {
                    b.HasOne("PatientTrackerWPF.Models.User", "CreatedByUser")
                        .WithMany("ScoreEntriesCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PatientTrackerWPF.Models.User", "UpdatedByUser")
                        .WithMany("ScoreEntriesUpdated")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("PatientTrackerWPF.Models.User", b =>
                {
                    b.Navigation("ScoreEntriesCreated");

                    b.Navigation("ScoreEntriesUpdated");
                });
#pragma warning restore 612, 618
        }
    }
}
